### PR TITLE
overlay: Add Kubernetes

### PR DESCRIPTION
**Pull request by cgwalters**
We'll track Fedora for this.

### CODE REVIEW

**Comment by jasonbrooks** [comment]
@cgwalters Did we get past the multi-source build issue?

**Comment by cgwalters** [comment]
We didn't - this is just rebuilding what's in Fedora dist-git, it's not tracking upstream git yet.

**Comment by cgwalters** [comment]
This does build though, i tested it locally.  And I do see it as valuable to version lock CAHC with Fedora.

**Comment by jasonbrooks** [comment]
Agreed, I'd like to settle on something similar w/ docker.

**Pull request merged**
