### PR TITLE
update metadata for 7.1804, sync with upstream formatting convention

### PR DESCRIPTION
**Pull request by jasonbrooks**

### CODE REVIEW

**Comment by cgwalters** [comment]
Is this synced with the most recent released metadata or from internal git?  I see some things here which make me thing it's post-7.5.0.

**Comment by cgwalters** [comment]
Specifically I don't see `podman` in 7.5.0 right?

**Comment by jasonbrooks** [comment]
I'll double check, but I'm pretty sure I copied from jsons marked 7.5

**Comment by cgwalters** [comment]
Thanks, looks reasonable to me!

**Pull request merged**
