### PR TITLE
downstream: Drop mutate-os-release

### PR DESCRIPTION
**Pull request by cgwalters**
It doesn't work yet because we don't have the new release package.

### CODE REVIEW

**Comment by jasonbrooks** [comment]
Regarding these drops, we're not going to release downstream until the new pkgs are built -- are we making these changes in the interim for the convenience of people doing custom builds?

**Comment by cgwalters** [comment]
Yep, I point people at the `downstream` branch generally expecting things to work.

**Comment by cgwalters** [comment]
Now, maybe what we could do is introduce git tags, like `downstream-$releasever`.

**Comment by jasonbrooks** [comment]
I originally intended to hold off on merging the #184 until we had the pkgs in place -- next time I'll put a WIP or something in the PR.

**Comment by cgwalters** [comment]
I think we should do git tags regardless though.

**Pull request merged**
