### PR TITLE
bump version, change scheme to match monthly centos releases

### PR DESCRIPTION
**Pull request by jasonbrooks**

### CODE REVIEW

**Comment by jasonbrooks** [comment]
@cgwalters will it be a problem for us to modify our numbering scheme this way -- like will 7.20170428 register as being larger than 7.1705?

**Comment by cgwalters** [comment]
There are no semantics in ostree for versions, they're purely for human consumption.  The versions could equally well be `apple` → `🧀` → `42` → `7`.

**Comment by cgwalters** [comment]
(Although for rpm-ostree the `automatic_version_prefix` does try to increment, but I think that should be fine)

**Comment by jlebon** [comment]
I just had to try this, but unfortunately, glib barfs :(

```
# ostree commit -b tmp --tree=ref=vmcheck --add-metadata-string=version='🧀'
error: Invalid byte sequence in conversion input
```

There goes all my dreams of food item based versioning.

**Comment by cgwalters** [comment]
Hm, it works fine for me here:
```
[root@localhost ~]# ostree commit -b tmp --tree=dir=. --add-metadata-string=version='🧀'
eb0dc4bf1f76a811b8eb779c1132f0b409701bcb1e37ec6c808326160e3d0ee2
[root@localhost ~]# rpm-ostree status
State: idle
Deployments:
● fedora-atomic:fedora-atomic/25/x86_64/docker-host
             Version: 25.113 (2017-04-25 01:47:29)
              Commit: 3492546bc1ef6bca1bc7801ed6bb0414f90cc96668e067996dba3dee0d83e6c3
              OSName: fedora-atomic
[root@localhost ~]# ostree show tmp
commit eb0dc4bf1f76a811b8eb779c1132f0b409701bcb1e37ec6c808326160e3d0ee2
Date:  2017-06-01 20:56:37 +0000
Version: 🧀
(no subject)
```

**Pull request merged**
