### PR TITLE
overlay: Freeze ostree temporarily

### PR DESCRIPTION
**Pull request by cgwalters**

### CODE REVIEW

**Comment by cgwalters** [comment]
This gets us out of a circular deadlock - our commits to rpm-ostree are gated on rdgo, but the rdgo build is broken.

**Comment by jlebon** [comment]
But then https://github.com/projectatomic/rpm-ostree/pull/991 won't go through, right?

**Comment by cgwalters** [comment]
Yeah...hm.    I'll do a PR for rpm-ostree to build with both options.

**Comment by jlebon** [comment]
Ahh I see the problem, right. LGTM!

**Comment by cgwalters** [comment]
I have a new idea ⬆️

**Comment by jlebon** [comment]
Right, that makes sense. 👍

**Pull request merged**
