### PR TITLE
add gomtree, mutate-os-release

### PR DESCRIPTION
**Pull request by jasonbrooks**

### CODE REVIEW

**Comment by jasonbrooks** [comment]
I'm not able to compose a tree with this atm:

```
Mutating /etc/os-release

(rpm-ostree compose tree:11952): GLib-CRITICAL **: g_regex_replace_literal: assertion 'replacement != NULL' failed
[root@localhost sig-atomic-buildscripts]# rpm -q rpm-ostree
rpm-ostree-2016.13-1.atomic.el7.x86_64
```

**Comment by jlebon** [comment]
This should be fixed by https://github.com/projectatomic/rpm-ostree/pull/603.

**Comment by jasonbrooks** [comment]
OK, cool, we'll just hang on to this until that rpm-ostree makes its way into CentOS.

**Comment by cgwalters** [comment]
Hm, is the bug here that you weren't providing an initial version?

**Comment by jlebon** [comment]
Right, I should have been more explicit here. There is neither an automatic prefixing nor a version specified by `--add-metadata-string`. All https://github.com/projectatomic/rpm-ostree/pull/603 does is make sure we handle this case gracefully, though you probably still want to do one of the above.

**Comment by cgwalters** [comment]
Ok, so if I'm understanding correctly, @jasonbrooks could do test composes by specifying a version now, right?

**Comment by jasonbrooks** [comment]
Ok, this should work, then, because we do supply the string in the build script. We do `--add-metadata-string=version=${VERSION}` where `VERSION=7.$( date  +%Y%m%d )`. Would it be better to integrate this into the json?

**Comment by jlebon** [comment]
`mutate-os-release` right now won't integrate versions given from `--add-metadata-string` into `os-release` (https://github.com/projectatomic/rpm-ostree/pull/603 fixes that too). So right, you'd have to make it part of the json using `automatic_version_prefix` if you want that mutation to happen.

**Comment by jasonbrooks** [comment]
Would a date-based automatic prefix work?

**Comment by jlebon** [comment]
You can just ignore the "automatic" part of it and set `automatic_version_prefix` to e.g. `"7.20170201"`. Since the previous commit won't have that prefix, it will just set it to that exact string. Once this is fixed upstream, you can go back to doing this properly with `--add-metadata-string`.

**Comment by jasonbrooks** [comment]
OK, I'm going to merge and test

**Comment by jasonbrooks** [comment]
@jlebon OK, that didn't work: https://ci.centos.org/job/Atomic_Host_DownStream/263/consoleText

Did I do it wrong?

```
Mutating /etc/os-release

(rpm-ostree compose tree:13795): GLib-CRITICAL **: g_regex_replace_literal: assertion 'replacement != NULL' failed
```

**Comment by jlebon** [comment]
Ahh, but you still specified `--add-metadata-string=version=7.20170201`, so then the automatic prefix from the json didn't have any effect. :) Try removing that arg.

**Pull request merged**
