### PR TITLE
overlay: Add commissaire dependencies

### PR DESCRIPTION
**Pull request by mbarnes**
Untested, but I believe this is everything Commissaire needs.

### CODE REVIEW

**Comment by mbarnes** [comment]
@cgwalters ^^

**Comment by cgwalters** [comment]
A few things:

 - The order in the list is the order in which things are built, so dependencies should go before commissiare in the list
 - The distgit: refers to *source* names not binaries, so we need to drop the `2` from the python packages

**Comment by mbarnes** [comment]
> The order in the list is the order in which things are built, so dependencies should go before commissiare in the list

Does order matter for Python modules?  They're all runtime dependencies; no linking.  But I can reorder just to keep the layout consistent.

**Comment by mbarnes** [comment]
:arrow_up: Corrected.

**Comment by cgwalters** [comment]
Looks like a lot of things are broken due to this base root:

```
DEBUG util.py:417:  Getting requirements for py-bcrypt-0.4-c061a55d4885817b6c3c88212ed1364424f31e78.el7.centos.src
DEBUG util.py:417:   --> python-devel-2.7.5-34.el7.x86_64
DEBUG util.py:417:  Error: No Package found for python3-devel
```

So to make this work we'll need to land changes in the spec files like the conditionals that landed in http://pkgs.fedoraproject.org/cgit/rpms/python-docker-py.git/log/

**Comment by cgwalters** [comment]
At a high level I'd say it's up to you at the moment whether going through this excercise is worth it now.  For the Atomic Host portion I feel it's been essential, but maybe instead we could say commmisaire comes as just a Fedora container?

**Comment by mbarnes** [comment]
Looks like crud I'll have to deal with anyway to if we still want Commissaire in RHEL.  A Fedora container may end up the better (maybe only) option but I'll still see if I can make any headway.

**Comment by cgwalters** [comment]
Yeah.  The biggest pain point is that Fedora has newer Python macros like `%py2_install` that aren't in CentOS `redhat-rpm-config` yet.

In python-docker we ended up copying them in...but we could try to create a package for them like is done with `go-srpm-macros`.

Really what we want long term is to auto-generate spec files.

**Comment by cgwalters** [comment]
Not relevant anymore since Commissaire is going to go into a container, and (currently) the CAHC content isn't feeding into any containers.  If we wanted to re-scope that in it'd be a new patch.

**Pull request closed without merging**
