### PR TITLE
rdgo: New directory for rpmdistro-gitoverlay

### PR DESCRIPTION
**Pull request by cgwalters**
We'll use the Fedora (23 mostly) spec files to build on CentOS (released).

This necessitates pulling in some newer versions of dependencies like
python-docker-py.

### CODE REVIEW

**Comment by cgwalters** [comment]
Don't merge this yet, it's a WIP.  Will post on the list.

**Comment by cgwalters** [comment]
https://lists.projectatomic.io/projectatomic-archives/atomic-devel/2016-April/msg00004.html

**Comment by cgwalters** [comment]
I know none of this will run outside my laptop, have to remove the hardcoded `file:///` references to my local mirror, etc.

**Comment by cgwalters** [comment]
Ok, I upstreamed my patches to the spec files, pushed a `fixup!`.

**Comment by cgwalters** [comment]
I've (possibly temporarily) migrated this to https://github.com/cgwalters/continuous-atomic-overlay

**Comment by cgwalters** [comment]
Okay, things are in a better place now in https://github.com/cgwalters/continuous-atomic-overlay/

What do you think about merging the overlay into this repo?  The big question is how much we make the downstream builds resemble the CI builds.  That's going to be a tricky topic over time.

But my strawman suggestion is to replace the `build_stage*.sh` scripts etc. with what's in c-a-o right now.  That means we lose support for generating VM/ISO images, but I'd like to iterate on re-adding that.

**Comment by jasonbrooks** [comment]
I was thinking about just adding the artifacts dir from the ci as another repo. I actually did a test build yesterday that did just this.

**Comment by cgwalters** [comment]
I just merged ostree commit generation into the JJB:
https://github.com/cgwalters/continuous-atomic-overlay/commit/f1a3149516d0dc24c1be83923a22124b8bcef757
and following.

That said, I think it would make sense to change the devel branch to
point at the rdgo by default too, that would simplify things.

**Comment by cgwalters** [comment]
Okay, so...what do you think about merging the rest of continuous-atomic-overlay into this repo?

**Comment by jasonbrooks** [comment]
Fine with me

**Comment by cgwalters** [comment]
Oops, sorry - this PR was old.  I can try rebasing now, though it might be simpler to revert.  I'll look.

**Pull request merged**
