### PR TITLE
don't try to remove centos-logos

### PR DESCRIPTION
**Pull request by jasonbrooks**
see https://ci.centos.org/job/Atomic_Host_DownStream/296/consoleText

### CODE REVIEW

**Comment by cgwalters** [comment]
Hmm.  I have an old cah vagrant box sitting around and:

```
# rpm-ostree status
State: idle
Deployments:
● centos-atomic-host:centos-atomic-host/7/x86_64/standard
             Version: 7.1707 (2017-07-31 16:12:06)
              Commit: 0bf6200211dd4fd63be6e9bc5c90bea645e2696c0117b05f83562081813a5b94
        GPGSignature: 1 signature
                      Signature made Mon 31 Jul 2017 04:42:00 PM UTC using RSA key ID F17E745691BA8335
                      Good signature from "CentOS Atomic SIG <security@centos.org>"
-bash-4.2# rpm -q centos-logos
centos-logos-70.0.6-3.el7.centos.noarch
```

**Comment by jasonbrooks** [comment]
@cgwalters So, it appears that centos-logos wasn't being removed after all there?

I'm testing a compose of what will be the next cah in the ci, and I'm getting stopped on `error: Postprocessing: Unable to find package 'centos-logos' specified in remove-from-packages`

**Comment by cgwalters** [comment]
I suspect something is no longer pulling it in as a dependency?

**Comment by jasonbrooks** [comment]
OK, so this is good to merge?

**Comment by cgwalters** [comment]
This patch shouldn't break anything, so should be fine to merge from that perspective.

It's fine by me if the logos package goes away too; AFAIK for servers it's only used for GRUB splash screen (I don't care personally) and potentially plymouth but we don't ship that.

It might be worth investigating *why* it went away...but eh.

**Comment by cgwalters** [comment]
(I just checked and there's no `centos-logos` in `registry.centos.org/centos/centos:7` at least.

**Comment by jasonbrooks** [comment]
I'll poke around some more into where this went.

**Comment by jasonbrooks** [comment]
@cgwalters I think I found it -- grub2 used to [require system-logos](https://git.centos.org/blob/rpms!grub2.git/23d2ea7ed7d0b099004f78517adff7df35855530/SPECS!grub2.spec#L129), which is satisfied in centos by centos-logos. I also need to remove a couple other bits from the json that centos-logos had been bringing in and we were removing.

**Pull request merged**
